- name: Initialize Docker Swarm manager
  hosts: swarm_managers
  become: true

  roles:
    - role: swarm
      tasks_from: manager.yml


- name: Join Docker Swarm workers
  hosts: swarm_workers
  become: true

  roles:
    - role: swarm
      tasks_from: workers.yml


- name: Configure Docker Swarm worker labels
  hosts: swarm_managers
  become: true

  roles:
    - role: swarm
      tasks_from: labels.yml