- name: Initialize Docker Swarm manager
  hosts: swarm_managers
  become: true

  tasks:
    - name: Run Docker Swarm manager tasks
      ansible.builtin.import_role:
        name: swarm
        tasks_from: manager


- name: Join Docker Swarm workers
  hosts: swarm_workers
  become: true

  tasks:
    - name: Run Docker Swarm worker tasks
      ansible.builtin.import_role:
        name: swarm
        tasks_from: workers


- name: Configure Docker Swarm worker labels
  hosts: swarm_managers
  become: true

  tasks:
    - name: Run Docker Swarm label tasks
      ansible.builtin.import_role:
        name: swarm
        tasks_from: labels