- name: Wait until worker nodes are visible in Swarm
  ansible.builtin.command:
    argv:
      - docker
      - node
      - inspect
      - "{{ item }}"
  loop: "{{ groups['swarm_workers'] }}"
  register: swarm_worker_node_check
  changed_when: false
  retries: 10
  delay: 3
  until: swarm_worker_node_check.rc == 0

- name: Check worker node labels
  ansible.builtin.command:
    argv:
      - docker
      - node
      - inspect
      - --format
      - "{{ '{{' }} index .Spec.Labels \"{{ item.1.key }}\" {{ '}}' }}"
      - "{{ item.0 }}"
  loop: "{{ groups['swarm_workers'] | product(swarm_worker_labels | dict2items) | list }}"
  loop_control:
    label: "{{ item.0 }}: {{ item.1.key }}={{ item.1.value }}"
  register: swarm_worker_label_check
  changed_when: false

- name: Add role=worker label to worker nodes
  ansible.builtin.command:
    argv:
      - docker
      - node
      - update
      - --label-add
      - "{{ item.item.1.key }}={{ item.item.1.value }}"
      - "{{ item.item.0 }}"
  loop: "{{ swarm_worker_label_check.results }}"
  loop_control:
    label: "{{ item.item.0 }}: {{ item.item.1.key }}={{ item.item.1.value }}"
  when: item.stdout != item.item.1.value