[task1]
t1-01 ansible_host=10.20.0.31 proxmox_id=601 proxmox_type=container
t1-02 ansible_host=10.20.0.32 proxmox_id=602 proxmox_type=container
t1-03 ansible_host=10.20.0.33 proxmox_id=603 proxmox_type=container

[all:children]
task1

[all:vars]
ansible_ssh_common_args='-o ProxyJump=gw-01 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'