[task1]
t1-01 ansible_host=10.20.0.31 ansible_user=root proxmox_id=601 proxmox_type=container
t1-02 ansible_host=10.20.0.32 ansible_user=root proxmox_id=602 proxmox_type=container
t1-03 ansible_host=10.20.0.33 ansible_user=root proxmox_id=603 proxmox_type=container

[all:children]
task1